export { SupportedTags } from './factory'
export { VirtualDOM, RxHTMLElement } from './virtual-dom'
export * as API from './api'
export * as TypeUtils from './type-utils'
export { render } from './core'
